import React from "react";
const columns = [
  { name: "Weeks", uid: "weeks" },
  { name: "Sun", uid: "sun" },
  { name: "Mon", uid: "mon" },
  { name: "Tue", uid: "tue" },
  { name: "Wed", uid: "wed" },
  { name: "Thr", uid: "thr" },
  { name: "Fri", uid: "fri" },
  { name: "Sat", uid: "sat" },
];

const users = [
  {
    weeks: 'Week 1',
    sun: "checkbox",
    mon: "checkbox",
    tue: "checkbox",
    wed: "checkbox",
    thr: "checkbox",
    fri: "checkbox",
    sat: "checkbox",
  },
  {
    weeks: 'Week 2',
    sun: "checkbox",
    mon: "checkbox",
    tue: "checkbox",
    wed: "checkbox",
    thr: "checkbox",
    fri: "checkbox",
    sat: "checkbox",
  },
  {
    weeks: 'Week 3',
    sun: "checkbox",
    mon: "checkbox",
    tue: "checkbox",
    wed: "checkbox",
    thr: "checkbox",
    fri: "checkbox",
    sat: "checkbox",
  },
  {
    weeks: 'Week 4',
    sun: "checkbox",
    mon: "checkbox",
    tue: "checkbox",
    wed: "checkbox",
    thr: "checkbox",
    fri: "checkbox",
    sat: "checkbox",
  },
  {
    weeks: 'Week 5',
    sun: "checkbox",
    mon: "checkbox",
    tue: "checkbox",
    wed: "checkbox",
    thr: "checkbox",
    fri: "checkbox",
    sat: "checkbox",
  },
  {
    weeks: 'Week 6',
    sun: "checkbox",
    mon: "checkbox",
    tue: "checkbox",
    wed: "checkbox",
    thr: "checkbox",
    fri: "checkbox",
    sat: "checkbox",
  },
  {
    weeks: 'Week 7',
    sun: "checkbox",
    mon: "checkbox",
    tue: "checkbox",
    wed: "checkbox",
    thr: "checkbox",
    fri: "checkbox",
    sat: "checkbox",
  }
];
//   {
//     id: 2,
//     name: "Zoey Lang",
//     role: "Technical Lead",
//     team: "Development",
//     status: "paused",
//     age: "25",
//     email: "zoey.lang@example.com",
//   },
//   {
//     id: 3,
//     name: "Jane Fisher",
//     role: "Senior Developer",
//     team: "Development",
//     status: "active",
//     age: "22",
//     email: "jane.fisher@example.com",
//   },
//   {
//     id: 4,
//     name: "William Howard",
//     role: "Community Manager",
//     team: "Marketing",
//     status: "vacation",
//     age: "28",
//     email: "william.howard@example.com",
//   },
//   {
//     id: 5,
//     name: "Kristen Copper",
//     role: "Sales Manager",
//     team: "Sales",
//     status: "active",
//     age: "24",
//     email: "kristen.cooper@example.com",
//   },
// ];

export { columns, users };
