import { IFormData } from "@/types/form";
import { IColumns } from "@/types/table";

const columns: IColumns[] = [
  { name: "Bill No", uid: "BillNo" },
  { name: "Bill Date", uid: "BillDate" },
  { name: "Bill Mode", uid: "BillMode" },
  { name: "Salesman", uid: "Salesman" },
  { name: "Route", uid: "Route" },
  { name: "Channel", uid: "Channel" },
  { name: "Sub Channel", uid: "Subchannel" },
  { name: "Retailer Code", uid: "RetailerCode" },
  { name: "Retailer name", uid: "RetailerName" },
  { name: "Quantity (Case)", uid: "Quantity(CASE)" },
  { name: "Quantity (Each)", uid: "Quantity(EACH)" },
  { name: "Gross Amount", uid: "Gross Amount", type: "float" },
  { name: "Taxable Amount", uid: "Taxable Amount", type: "float" },
  { name: "Vat Amount", uid: "Vat Amount", type: "float" },
  { name: "Net Amount", uid: "Net Amount", type: "float" },
  { name: "Round Off", uid: "Round Off" },
];

const tableData = [
  {
    BillNo: "TI1-AJI-80/81",
    BillDate: "7/17/2023",
    BillMode: "credit",
    Salesman: "Subash Majhi",
    Route: "Chundevi, Panchakanya",
    Channel: "Groceries - Small",
    Subchannel: "Groceries - Small",
    RetailerCode: "NT0560313",
    RetailerName: "Daju Bhai Store",
    "Quantity(CASE)": "1",
    "Quantity(EACH)": "480",
    "Gross Amount": "3716.77242",
    "Taxable Amount": "2630.69613",
    "Vat Amount": "341.9904969",
    "Net Amount": "2973",
    "Round Off": "0.69",
  },
  {
    BillNo: "CN1-AJI-80/81",
    BillDate: "10/2/2023",
    BillMode: "credit",
    Salesman: "Subash Majhi",
    Route: "Chandol",
    Channel: "Groceries - Small",
    Subchannel: "Groceries - Small",
    RetailerCode: "NT0560202",
    RetailerName: "Amrit Kirana Store",
    "Quantity(CASE)": "-2",
    "Quantity(EACH)": "0",
    "Gross Amount": "-31407.88416",
    "Taxable Amount": "-31407.88416",
    "Vat Amount": "-4083.024941",
    "Net Amount": "-35491",
    "Round Off": "-0.09",
  },
  {
    BillNo: "CN2-AJI-80/81",
    BillDate: "10/2/2023",
    BillMode: "credit",
    Salesman: "Subash Majhi",
    Route: "Chandol",
    Channel: "Groceries - Small",
    Subchannel: "Groceries - Small",
    RetailerCode: "NT0560282",
    RetailerName: "Presha Store&Suppliers",
    "Quantity(CASE)": "-3",
    "Quantity(EACH)": "0",
    "Gross Amount": "-38075.62349",
    "Taxable Amount": "-38075.62349",
    "Vat Amount": "-4949.831053",
    "Net Amount": "-43025",
    "Round Off": "-0.55",
  },
  {
    BillNo: "TI2-AJI-80/81",
    BillDate: "7/17/2023",
    BillMode: "credit",
    Salesman: "Subash Majhi",
    Route: "Chandol",
    Channel: "Groceries - Small",
    Subchannel: "Groceries - Small",
    RetailerCode: "NT0560202",
    RetailerName: "Amrit Kirana Store",
    "Quantity(CASE)": "0",
    "Quantity(EACH)": "4",
    "Gross Amount": "1586.484312",
    "Taxable Amount": "1574.484312",
    "Vat Amount": "204.6829606",
    "Net Amount": "1779",
    "Round Off": "0.17",
  },
  {
    BillNo: "TI3-AJI-80/81",
    BillDate: "7/17/2023",
    BillMode: "credit",
    Salesman: "Subash Majhi",
    Route: "Chandol",
    Channel: "Groceries - Small",
    Subchannel: "Groceries - Small",
    RetailerCode: "NT0560285",
    RetailerName: "Raju Pasal ",
    "Quantity(CASE)": "0",
    "Quantity(EACH)": "300",
    "Gross Amount": "3485.098536",
    "Taxable Amount": "3291.944875",
    "Vat Amount": "427.9528338",
    "Net Amount": "3720",
    "Round Off": "0.9",
  },
  {
    BillNo: "CN3-AJI-80/81",
    BillDate: "10/2/2023",
    BillMode: "credit",
    Salesman: "Subash Majhi",
    Route: "Chundevi, Panchakanya",
    Channel: "Chemists",
    Subchannel: "Chemists",
    RetailerCode: "NT0560206",
    RetailerName: "Yuliana Pharmacy",
    "Quantity(CASE)": "-5",
    "Quantity(EACH)": "0",
    "Gross Amount": "-78777.11184",
    "Taxable Amount": "-78777.11184",
    "Vat Amount": "-10241.02454",
    "Net Amount": "-89018",
    "Round Off": "-0.86",
  },
  {
    BillNo: "CN4-AJI-79/80",
    BillDate: "4/16/2023",
    BillMode: "credit",
    Salesman: "Subash Majhi",
    Route: "Baluwatar",
    Channel: "Groceries - Small",
    Subchannel: "Groceries - Small",
    RetailerCode: "NT0560255",
    RetailerName: "Krishna Store (A)",
    "Quantity(CASE)": "-1",
    "Quantity(EACH)": "-18",
    "Gross Amount": "-10542.22363",
    "Taxable Amount": "-10542.22363",
    "Vat Amount": "-1370.489072",
    "Net Amount": "-11913",
    "Round Off": "-0.29",
  },
  {
    BillNo: "TI4-AJI-80/81",
    BillDate: "7/17/2023",
    BillMode: "credit",
    Salesman: "Subash Majhi",
    Route: "Chundevi, Panchakanya",
    Channel: "Chemists",
    Subchannel: "Chemists",
    RetailerCode: "NT0560206",
    RetailerName: "Yuliana Pharmacy",
    "Quantity(CASE)": "0",
    "Quantity(EACH)": "2",
    "Gross Amount": "820.594664",
    "Taxable Amount": "820.594664",
    "Vat Amount": "106.6773063",
    "Net Amount": "927",
    "Round Off": "0.27",
  },
  {
    BillNo: "CN5-AJI-79/80",
    BillDate: "4/21/2023",
    BillMode: "",
    Salesman: "Hari Bhattarai",
    Route: "Budhnilkantha",
    Channel: "Chemists",
    Subchannel: "Chemists",
    RetailerCode: "NT0560033",
    RetailerName: "Narayanthan Pharmacy",
    "Quantity(CASE)": "0",
    "Quantity(EACH)": "-24",
    "Gross Amount": "-12217.20836",
    "Taxable Amount": "-12095.03628",
    "Vat Amount": "-1572.354716",
    "Net Amount": "-13667",
    "Round Off": "-0.61",
  },
  {
    BillNo: "TI5-AJI-80/81",
    BillDate: "7/17/2023",
    BillMode: "credit",
    Salesman: "Subash Majhi",
    Route: "Chundevi, Panchakanya",
    Channel: "Paan Plus",
    Subchannel: "Paan Plus",
    RetailerCode: "NT0560204",
    RetailerName: "Pangmalee Store & Liquor Shop",
    "Quantity(CASE)": "0",
    "Quantity(EACH)": "252",
    "Gross Amount": "4464.812878",
    "Taxable Amount": "4408.611307",
    "Vat Amount": "573.1194699",
    "Net Amount": "4982",
    "Round Off": "0.73",
  },
  {
    BillNo: "TI6-AJI-80/81",
    BillDate: "7/17/2023",
    BillMode: "credit",
    Salesman: "Subash Majhi",
    Route: "Dhumbarahi",
    Channel: "Groceries - Small",
    Subchannel: "Groceries - Small",
    RetailerCode: "NT0560213",
    RetailerName: "Chitawan Store",
    "Quantity(CASE)": "0",
    "Quantity(EACH)": "310",
    "Gross Amount": "2951.153793",
    "Taxable Amount": "2931.591464",
    "Vat Amount": "381.1068903",
    "Net Amount": "3313",
    "Round Off": "0.7",
  },
  {
    BillNo: "TI7-AJI-80/81",
    BillDate: "7/17/2023",
    BillMode: "credit",
    Salesman: "Subash Majhi",
    Route: "Hadigan,Maligan Gahanapokhari",
    Channel: "Groceries - Small",
    Subchannel: "Groceries - Small",
    RetailerCode: "NT0560184",
    RetailerName: "Jaiswal kirana Store",
    "Quantity(CASE)": "0",
    "Quantity(EACH)": "385",
    "Gross Amount": "4705.696693",
    "Taxable Amount": "4603.10613",
    "Vat Amount": "598.4037969",
    "Net Amount": "5202",
    "Round Off": "0.51",
  },
  {
    BillNo: "TI8-AJI-80/81",
    BillDate: "7/17/2023",
    BillMode: "credit",
    Salesman: "Subash Majhi",
    Route: "Hadigan,Maligan Gahanapokhari",
    Channel: "Groceries - Small",
    Subchannel: "Groceries - Small",
    RetailerCode: "NT0560194",
    RetailerName: "Rai Ko Kirana Pasal(Handigaun)",
    "Quantity(CASE)": "0",
    "Quantity(EACH)": "42",
    "Gross Amount": "652.072344",
    "Taxable Amount": "639.0308971",
    "Vat Amount": "83.07401663",
    "Net Amount": "722",
    "Round Off": "0.1",
  },
  {
    BillNo: "TI9-AJI-80/81",
    BillDate: "7/17/2023",
    BillMode: "credit",
    Salesman: "Subash Majhi",
    Route: "Hadigan,Maligan Gahanapokhari",
    Channel: "Groceries - Small",
    Subchannel: "Groceries - Small",
    RetailerCode: "NT0560192",
    RetailerName: "R.B. Khadya Store",
    "Quantity(CASE)": "0",
    "Quantity(EACH)": "75",
    "Gross Amount": "1583.607258",
    "Taxable Amount": "1551.935113",
    "Vat Amount": "201.7515647",
    "Net Amount": "1754",
    "Round Off": "0.69",
  },
  {
    BillNo: "TI10-AJI-80/81",
    BillDate: "7/17/2023",
    BillMode: "credit",
    Salesman: "Subash Majhi",
    Route: "Hadigan,Maligan Gahanapokhari",
    Channel: "Groceries - Small",
    Subchannel: "Groceries - Small",
    RetailerCode: "NT0560181",
    RetailerName: "Bina kirana Store",
    "Quantity(CASE)": "0",
    "Quantity(EACH)": "597",
    "Gross Amount": "2831.660262",
    "Taxable Amount": "2812.097933",
    "Vat Amount": "365.5727313",
    "Net Amount": "3178",
    "Round Off": "0.67",
  },
  {
    BillNo: "TI11-AJI-80/81",
    BillDate: "7/17/2023",
    BillMode: "credit",
    Salesman: "Subash Majhi",
    Route: "Hadigan,Maligan Gahanapokhari",
    Channel: "Groceries - Small",
    Subchannel: "Groceries - Small",
    RetailerCode: "NT0560196",
    RetailerName: "Rishika Store",
    "Quantity(CASE)": "0",
    "Quantity(EACH)": "390",
    "Gross Amount": "1983.88473",
    "Taxable Amount": "1976.402841",
    "Vat Amount": "256.9323694",
    "Net Amount": "2233",
    "Round Off": "0.34",
  },
  {
    BillNo: "TI12-AJI-80/81",
    BillDate: "7/17/2023",
    BillMode: "credit",
    Salesman: "Subash Majhi",
    Route: "Hadigan,Maligan Gahanapokhari",
    Channel: "Groceries - Small",
    Subchannel: "Groceries - Small",
    RetailerCode: "NT0560193",
    RetailerName: "Radha Cold store",
    "Quantity(CASE)": "0",
    "Quantity(EACH)": "21",
    "Gross Amount": "978.116454",
    "Taxable Amount": "958.5541249",
    "Vat Amount": "124.6120362",
    "Net Amount": "1083",
    "Round Off": "0.17",
  },
  {
    BillNo: "TI13-AJI-80/81",
    BillDate: "7/17/2023",
    BillMode: "credit",
    Salesman: "Subash Majhi",
    Route: "Hadigan,Maligan Gahanapokhari",
    Channel: "Groceries - Small",
    Subchannel: "Groceries - Small",
    RetailerCode: "NT0560277",
    RetailerName: "Deepak Cold Store",
    "Quantity(CASE)": "0",
    "Quantity(EACH)": "21",
    "Gross Amount": "978.116454",
    "Taxable Amount": "958.5541249",
    "Vat Amount": "124.6120362",
    "Net Amount": "1083",
    "Round Off": "0.17",
  },
  {
    BillNo: "TI14-AJI-80/81",
    BillDate: "7/17/2023",
    BillMode: "credit",
    Salesman: "Subash Majhi",
    Route: "Hadigan,Maligan Gahanapokhari",
    Channel: "Groceries - Small",
    Subchannel: "Groceries - Small",
    RetailerCode: "NT0560201",
    RetailerName: "Tangal Kirana Store",
    "Quantity(CASE)": "0",
    "Quantity(EACH)": "234",
    "Gross Amount": "1269.92028",
    "Taxable Amount": "1256.878833",
    "Vat Amount": "163.3942483",
    "Net Amount": "1420",
    "Round Off": "0.27",
  },
  {
    BillNo: "TI15-AJI-80/81",
    BillDate: "7/17/2023",
    BillMode: "credit",
    Salesman: "Subash Majhi",
    Route: "Hadigan,Maligan Gahanapokhari",
    Channel: "Groceries - Small",
    Subchannel: "Groceries - Small",
    RetailerCode: "NT0560186",
    RetailerName: "Lali Store",
    "Quantity(CASE)": "0",
    "Quantity(EACH)": "201",
    "Gross Amount": "3334.660753",
    "Taxable Amount": "3322.660753",
    "Vat Amount": "431.9458979",
    "Net Amount": "3755",
    "Round Off": "0.61",
  },
];
const filterFormData: IFormData[] = [
  {
    title: "",
    children: [
      {
        type: "row",
        title: "",
        children: [
          {
            type: "date",
            name: "from_date",
            placeholder: "Enter Date",
            validation_regex: "",
            label: "From: (AD)",
            optional: true,
          },
          {
            type: "date",
            name: "to_date",
            placeholder: "Enter Date",
            validation_regex: "",
            label: "To Date",
            optional: true,
          },
        ],
      },
      {
        type: "row",
        title: "",
        children: [
          {
            type: "text",
            name: "salesman",
            placeholder: "Enter  salesman",
            label: "Sales Man",
            validation_regex: "",
            optional: true,
          },
          {
            type: "text",
            name: "route",
            placeholder: "Enter Route",
            validation_regex: "",
            label: "Route",
            optional: true,
          },
        ],
      },
      {
        type: "row",
        title: "",
        children: [
          {
            type: "text",
            name: "retailer",
            placeholder: "Enter Retailer",
            validation_regex: "",
            label: "Retailer",
            optional: true,
          },
          {
            type: "text",
            name: "channel",
            placeholder: "Enter Channel",
            validation_regex: "",
            label: "Channel",
            optional: true,
          },
        ],
      },
      {
        type: "dropdown",
        name: "order_by",
        placeholder: "Select Order By",
        validation_regex: "",
        label: "Order By",
        dropdownItem: [
          {
            label: "1",
            value: "1",
          },
          {
            label: "2",
            value: "2",
          },
          {
            label: "3",
            value: "3",
          },
        ],
        optional: true,
      },
    ],
  },
];

export { columns, filterFormData, tableData };
